package main

import "golang.design/x/hotkey"

var keyMap = map[string]hotkey.Key{
	"KeySpace":  hotkey.KeySpace,
	"Key1":      hotkey.Key1,
	"Key2":      hotkey.Key2,
	"Key3":      hotkey.Key3,
	"Key4":      hotkey.Key4,
	"Key5":      hotkey.Key5,
	"Key6":      hotkey.Key6,
	"Key7":      hotkey.Key7,
	"Key8":      hotkey.Key8,
	"Key9":      hotkey.Key9,
	"Key0":      hotkey.Key0,
	"KeyA":      hotkey.KeyA,
	"KeyB":      hotkey.KeyB,
	"KeyC":      hotkey.KeyC,
	"KeyD":      hotkey.KeyD,
	"KeyE":      hotkey.KeyE,
	"KeyF":      hotkey.KeyF,
	"KeyG":      hotkey.KeyG,
	"KeyH":      hotkey.KeyH,
	"KeyI":      hotkey.KeyI,
	"KeyJ":      hotkey.KeyJ,
	"KeyK":      hotkey.KeyK,
	"KeyL":      hotkey.KeyL,
	"KeyM":      hotkey.KeyM,
	"KeyN":      hotkey.KeyN,
	"KeyO":      hotkey.KeyO,
	"KeyP":      hotkey.KeyP,
	"KeyQ":      hotkey.KeyQ,
	"KeyR":      hotkey.KeyR,
	"KeyS":      hotkey.KeyS,
	"KeyT":      hotkey.KeyT,
	"KeyU":      hotkey.KeyU,
	"KeyV":      hotkey.KeyV,
	"KeyW":      hotkey.KeyW,
	"KeyX":      hotkey.KeyX,
	"KeyY":      hotkey.KeyY,
	"KeyZ":      hotkey.KeyZ,
	"KeyReturn": hotkey.KeyReturn,
	"KeyEscape": hotkey.KeyEscape,
	"KeyDelete": hotkey.KeyDelete,
	"KeyTab":    hotkey.KeyTab,
	"KeyLeft":   hotkey.KeyLeft,
	"KeyRight":  hotkey.KeyRight,
	"KeyUp":     hotkey.KeyUp,
	"KeyDown":   hotkey.KeyDown,
	"KeyF1":     hotkey.KeyF1,
	"KeyF2":     hotkey.KeyF2,
	"KeyF3":     hotkey.KeyF3,
	"KeyF4":     hotkey.KeyF4,
	"KeyF5":     hotkey.KeyF5,
	"KeyF6":     hotkey.KeyF6,
	"KeyF7":     hotkey.KeyF7,
	"KeyF8":     hotkey.KeyF8,
	"KeyF9":     hotkey.KeyF9,
	"KeyF10":    hotkey.KeyF10,
	"KeyF11":    hotkey.KeyF11,
	"KeyF12":    hotkey.KeyF12,
	"KeyF13":    hotkey.KeyF13,
	"KeyF14":    hotkey.KeyF14,
	"KeyF15":    hotkey.KeyF15,
	"KeyF16":    hotkey.KeyF16,
	"KeyF17":    hotkey.KeyF17,
	"KeyF18":    hotkey.KeyF18,
	"KeyF19":    hotkey.KeyF19,
	"KeyF20":    hotkey.KeyF20,
}

var modifierMap = map[string]hotkey.Modifier{
	"ModCtrl":   hotkey.ModCtrl,
	"ModShift":  hotkey.ModShift,
	"ModOption": hotkey.ModOption,
	"ModCmd":    hotkey.ModCmd,
}
